apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-chart.fullname" . }}-headless
  labels:
    {{- include "minio-chart.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
  selector:
    {{- include "minio-chart.selectorLabels" . | nindent 4 }}

