apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minio-chart.fullname" . }}
  labels:
    {{- include "minio-chart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "minio-chart.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: minio
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - server
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.auth.rootUser | quote }}
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.auth.rootPassword | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: api
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "minio-chart.selectorLabels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass | quote }}
        {{- end }}

