image:
  repository: frontend-service
  tag: latest

containerPort: 4173

service:
  type: ClusterIP
  port: 80
  targetPort: http

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 200m
    memory: 256Mi
