apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kotlin-chart.fullname" . }}
  labels:
    {{- include "kotlin-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kotlin-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kotlin-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "kotlin-chart.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.secretEnv }}
            {{- range $key, $_ := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "kotlin-chart.fullname" $ }}-env
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          {{- else if .Values.secretEnv }}
          env:
            {{- range $key, $_ := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "kotlin-chart.fullname" $ }}-env
                  key: {{ $key }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
