apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo-chart.fullname" . }}-auth
  labels:
    {{- include "mongo-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.password | quote }}
