image:
  repository: mongo
  tag: "7.0"

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  size: 8Gi

auth:
  username: admin
  password: password
  database: master_data_db

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 200m
    memory: 256Mi
