providers:
  kubernetesGateway:
    enabled: true
  kubernetesIngress:
    enabled: false

gateway:
  enabled: false

gatewayClass:
  enabled: false

service:
  type: NodePort

ports:
  web:
    nodePort: 30088
  websecure:
    nodePort: 30443

logs:
  access:
    enabled: true

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 200m
    memory: 256Mi
