module.exports = [
  {
    id: 'users',
    scopes: ['users'],
    path: 'users-service',
    releasePaths: ['users-service/'],
    dockerfile: 'users-service/Dockerfile',
    image: 'users-service',
    publishDocker: true,
  },
  {
    id: 'master-data',
    scopes: ['master-data'],
    path: 'master-data-service',
    releasePaths: ['master-data-service/'],
    dockerfile: 'master-data-service/Dockerfile',
    image: 'master-data-service',
    publishDocker: true,
  },
  {
    id: 'frontend',
    scopes: ['frontend'],
    path: 'frontend-service',
    releasePaths: ['frontend-service/'],
    dockerfile: 'frontend-service/Dockerfile',
    image: 'frontend-service',
    publishDocker: true,
  },
  {
    id: 'appointments',
    scopes: ['appointments'],
    path: 'appointments-service',
    releasePaths: ['appointments-service/', 'build-logic/'],
    dockerfile: 'appointments-service/Dockerfile',
    image: 'appointments-service',
    publishDocker: true,
  },
  {
    id: 'documents',
    scopes: ['documents'],
    path: 'documents-service',
    releasePaths: ['documents-service/', 'build-logic/'],
    dockerfile: 'documents-service/Dockerfile',
    image: 'documents-service',
    publishDocker: true,
  },
  {
    id: 'ai',
    scopes: ['ai'],
    path: 'ai-service',
    releasePaths: ['ai-service/'],
    dockerfile: 'ai-service/Dockerfile',
    image: 'ai-service',
    publishDocker: true,
  },
  {
    id: 'commons',
    scopes: ['commons'],
    releasePaths: ['commons/'],
    publishDocker: false,
  },
];
