// Tag to color key mapping - Based on ServiceCategory enum
export const TAG_COLOR_MAP: Record<string, string> = {
  visita_specialistica: 'visita_specialistica',
  diagnostica_immagini: 'diagnostica_immagini',
  laboratorio: 'laboratorio',
  chirurgia: 'chirurgia',
  fisioterapia: 'fisioterapia',
  prevenzione: 'prevenzione',
  odontoiatria: 'odontoiatria',
  oculistica: 'oculistica',
  cardiologia: 'cardiologia',
  dermatologia: 'dermatologia',
  ortopedia: 'ortopedia',
  neurologia: 'neurologia',
  otorinolaringoiatria: 'otorinolaringoiatria',
  urologia: 'urologia',
  endocrinologia: 'endocrinologia',
  ginecologia: 'ginecologia',
  pediatria: 'pediatria',
  altro: 'altro',
};

// Tag to icon mapping - Based on ServiceCategory enum
export const TAG_ICON_MAP: Record<string, string> = {
  visita_specialistica: '👨‍⚕️',
  diagnostica_immagini: '📷',
  laboratorio: '🔬',
  chirurgia: '⚕️',
  fisioterapia: '💪',
  prevenzione: '🛡️',
  odontoiatria: '🦷',
  oculistica: '👁️',
  cardiologia: '❤️',
  dermatologia: '🧴',
  ortopedia: '🦴',
  neurologia: '🧠',
  otorinolaringoiatria: '👂',
  urologia: '💧',
  endocrinologia: '⚗️',
  ginecologia: '🩺',
  pediatria: '👶',
  altro: '📋',
};
